# Generated by Django 3.0.6 on 2020-05-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coreuserprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('summary', models.CharField(max_length=500)),
                ('skills', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WorkAccomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplishment', models.CharField(max_length=500)),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkExperience')),
            ],
        ),
    ]
