# Generated by Django 3.0.7 on 2020-08-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200808_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('is_draft', models.BooleanField(default=True)),
                ('date_published', models.DateField(auto_now=True)),
            ],
        ),
    ]
