# Generated by Django 3.0.7 on 2020-11-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_daysince'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaySince',
        ),
        migrations.AlterModelOptions(
            name='picturepost',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='textpost',
            options={'ordering': ['-id']},
        ),
    ]
