# Generated by Django 3.0.7 on 2020-12-02 23:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('potatofield', '0003_auto_20201130_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='jumbotron',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], default=None),
        ),
    ]
